Project/TaskManagementAppNew/TaskManagementAppNew/Controllers/LoginToController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagementAppNew.Models.BusinessModel;
using TaskManagementAppNew.Models.ViewModels;
using TaskManagementAppNew.Service;

namespace TaskManagementAppNew.Controllers
{
    public class LoginToController : Controller
    {
        // GET: LoginTo
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginVM vm)
        {
            User newUser = UserService.GetInstance().GetUser(vm.Email, vm.Password);
            if (newUser != null && newUser.IsAdmin == true)
            {
                Session["LoggedInUser"] = newUser.Name;
                Session["LoggedInId"] = newUser.Id;
                return RedirectToAction("Home", "Admin");
            }
            else if(newUser != null && newUser.IsAdmin == false && newUser.IsActive == true)
            {
                Session["LoggedInUser"] = newUser.Name;
                Session["LoggedInId"] = newUser.Id;
                return RedirectToAction("Home", "Task", new { id = Session["LoggedInId"] });

            }
            else
            {
                vm.LoginErrorMessage = "Invalid username or password!!";
                return View(vm);
            }

        }
        [AllowAnonymous]
        public ActionResult Logout()
        {
            
            HttpRuntime.UnloadAppDomain();
            Session.Abandon();
            return RedirectToAction("Login");
        }
    }
}

Project/TaskManagementAppNew/TaskManagementAppNew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Task Management System</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Task Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Aurionpro Solution Ltd.</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Project/TaskManagementAppNew/TaskManagementAppNew/Views/Shared/_MasterLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>_MasterLayout</title>
</head>
<body>
    <nav style="background-color:aqua">
        <div>
            <h2 style="text-align:center">
                @if (Session["LoggedInUser"] != null)
                {
                    <span style="border:ridge"> Welcome:@Session["LoggedInUser"]</span>
                    @Html.ActionLink("Logout", "Logout", "LoginTo", "", new {@class = "btn btn-danger"});
                }
            </h2>
        </div>

    </nav>
    <div>
        @RenderBody()
    </div>
</body>
</html>